import { useCallback, useEffect, useState } from "react";
import { RefreshCw } from "lucide-react";
import { api, apiMessage } from "@/lib/api";
import { AdminButton, AdminError, AdminLoading, Panel, StatusPill, shortDate } from "./AdminCommon";
export default function AdminSystem() { const [data, setData] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState(""); const load = useCallback(async () => { setLoading(true); setError(""); try {
    setData(await api("/admin/system"));
}
catch (e) {
    setError(apiMessage(e, "Unable to load system diagnostics"));
}
finally {
    setLoading(false);
} }, []); useEffect(() => { void load(); }, [load]); if (loading)
    return <AdminLoading label="Loading system diagnostics…"/>; if (error)
    return <AdminError message={error} retry={() => void load()}/>; return <div className="space-y-5"><div className="flex justify-end"><AdminButton tone="ghost" onClick={() => void load()}><RefreshCw size={15}/>Refresh</AdminButton></div><div className="grid gap-5 lg:grid-cols-2"><Panel title="Application"><dl className="grid grid-cols-2 gap-3 text-sm">{[["Name", data?.app?.name], ["Version", data?.app?.version], ["API version", data?.app?.apiVersion], ["Environment", data?.app?.environment]].map(([k, v]) => <div key={String(k)} className="rounded-xl bg-gray-50 p-3"><dt className="text-xs text-gray-500">{k}</dt><dd className="mt-1 font-semibold">{v || "—"}</dd></div>)}</dl></Panel><Panel title="Database"><dl className="grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-gray-50 p-3"><dt className="text-xs text-gray-500">Connection</dt><dd className="mt-1"><StatusPill tone={data?.database?.connected ? "success" : "danger"}>{data?.database?.connected ? "Connected" : "Disconnected"}</StatusPill></dd></div>{[["Database", data?.database?.name], ["Ping", data?.database?.pingMs == null ? "—" : `${data.database.pingMs} ms`], ["Topology", data?.database?.topology], ["Transactions", String(Boolean(data?.database?.transactionsEnabled))]].map(([k, v]) => <div key={String(k)} className="rounded-xl bg-gray-50 p-3"><dt className="text-xs text-gray-500">{k}</dt><dd className="mt-1 font-semibold">{v || "—"}</dd></div>)}</dl></Panel></div><Panel title="Runtime"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Node", data?.runtime?.node], ["Started", shortDate(data?.runtime?.startedAt)], ["Heap", `${data?.runtime?.memoryMb?.heapUsed ?? "—"} MB`], ["RSS", `${data?.runtime?.memoryMb?.rss ?? "—"} MB`], ["CPU user", `${data?.runtime?.cpu?.userMs ?? "—"} ms`], ["CPU system", `${data?.runtime?.cpu?.systemMs ?? "—"} ms`], ["Logical cores", data?.runtime?.cpu?.logicalCores], ["Load 1m", data?.runtime?.cpu?.loadAverage1m]].map(([k, v]) => <div key={String(k)} className="rounded-xl bg-gray-50 p-3"><p className="text-xs text-gray-500">{k}</p><p className="mt-1 font-semibold">{v}</p></div>)}</div></Panel><Panel title="Feature configuration"><div className="flex flex-wrap gap-2">{Object.entries(data?.features || {}).map(([k, v]) => <StatusPill key={k} tone={v ? "success" : "neutral"}>{k}: {v ? "configured" : "off"}</StatusPill>)}</div><p className="mt-4 text-xs text-gray-500">Secrets are intentionally not exposed or editable in this frontend.</p></Panel></div>; }
